version: "3.8"

services:
  react-app:
    container_name: todo-react-jenkins
    image: memoona2/todo-react-app:latest
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - .:/usr/src/app
    networks:
      - todo-net

  test-runner:
    build:
      context: .
    container_name: selenium-todo-tests
    depends_on:
      - react-app
    networks:
      - todo-net
    environment:
      - BASE_URL=http://react-app:3000
    command: ["python", "-m", "unittest", "discover", "-s", "tests"]

networks:
  todo-net:
